version: "2"

services:
  zookeeper:
    network_mode: host
    image: zookeeper:3.4.9
 
  mesos-master:
    image: mesosphere/mesos-master:1.1.0-2.0.107.ubuntu1404
    network_mode: host
    entrypoint:
      - mesos-master
    depends_on:
      - zookeeper
    environment:
      - MESOS_IP=127.0.0.1
      - MESOS_CLUSTER=local
      - MESOS_HOSTNAME=mesos-master.docker
      - MESOS_LOG_DIR=/var/log
      - MESOS_QUORUM=1
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_ZK=zk://127.0.0.1:2181/mesos

  mesos-slave:
    image: mesosphere/mesos-slave:1.1.0-2.0.107.ubuntu1404
    entrypoint:
      - mesos-slave
    privileged: true
    network_mode: host
    depends_on:
      - zookeeper
      - mesos-master
    environment:
      - MESOS_IP=127.0.0.1
      - MESOS_CONTAINERIZERS=mesos,docker
      - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
      - MESOS_ISOLATION=cgroups/cpu,cgroups/mem,docker/runtime
      - MESOS_LOG_DIR=var/log
      - MESOS_MASTER=zk://127.0.0.1:2181/mesos
      - MESOS_PORT=5051
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      - MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD=90secs
      - MESOS_DOCKER_STOP_TIMEOUT=60secs
      - MESOS_RESOURCES=ports(*):[11000-11999]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

  marathon-service:
    image:  mesosphere/marathon:latest
    network_mode: host
    depends_on:
      - zookeeper
      - mesos-master
    environment:
      - MARATHON_ZK=zk://127.0.0.1:2181/marathon
      - MARATHON_MASTER=zk://127.0.0.1:2181/mesos
